baseURL = "https://freebook-review.com/"
languageCode = "en-us"
title = "Free Book Review"
theme = "Octo"

enableRobotsTXT = true

[pagination]
pagerSize = 10

[taxonomies]
category = "categories"
tag      = "tags"

buildFuture = true